# volumes:
volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true

services:
  fastapi:
    environment:
      WAIT_HOSTS: postgres:5432
      CORS_HOST: http://localhost:5173
      DATABASE_URL: postgresql://gitfit:secret@postgres/gitfitdb
      SIGNING_KEY: ${SIGNING_KEY}
      API_KEY: ${API_KEY}
    build:
      context: api
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    # user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
    volumes:
      - ./ghi:/app
    ports:
      - "5173:5173"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      VITE_PUBLIC_URL: ${VITE_PUBLIC_URL}
      VITE_REACT_APP_API_HOST: ${VITE_REACT_APP_API_HOST}

  postgres:
    image: postgres:14.5-bullseye
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: gitfit
      POSTGRES_DB: gitfitdb
    ports:
      - 15432:5432

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: metest@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mepass
      PGADMIN_DISABLE_POSTFIX: 1
